### ISSUE TITLE
Review ontology

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V3#1]
Those are the topics we need to check with Thomas Francart:

1. In order to answer to LOV last requests mentioned here: https://github.com/datafoodconsortium/ontology/issues/10#issuecomment-622966539

We need to define:
- where to stock URI infos?
- for all metadata around business ontology how to deal with prefixes?

2. User connection and link to the ontology:

What type of class should we use? Is this included in DFC 's ontology or is this something on the side.

**Comment by simonLouvet** [comment]
échange et décision avec Thomas
0,25
