### ISSUE TITLE
various prefix for 4 OWL files

### ISSUE THREAD

**Issue by simonLouvet** [datafoodconsortium/dfc-prototype-V3#14]
1/ Nous avons 4 ontologies se traduisant par 4 fichier owl. LOV nous à par convention attribué des préfixes différents pour chaque fichier owl.
Vous devriez pouvoir contrôler ces préfixes avec des métadonnées vann dans vos ontologies (https://vocab.org/vann/#preferredNamespacePrefix).
ok 
Avez-vous bien lu les recommendations de documentation des ontologies dans LOV : https://lov.linkeddata.es/Recommendations_Vocabulary_Design.pdf ?
 oui
 
J'aimerai voir avec toi si, conceptuellement, nous pouvons avoir un seul préfixe pour les 4 fichiers.

A priori non. Si ce sont 4 ontologies, elles ont 4 espaces de nom différents, donc forcément 4 préfixes différents, on ne peut pas déclarer le même préfixe pour plusieurs espaces de noms.
ok, c'est ce que je craignais. Nous n'avons pas vraiment 4 ontologies mais 4 fichiers OWL (1 fichier full.owl qui agrège les 3 aspects de l'ontologie : technique, métier, glossaire). Est ce que tu as déjà rencontré ce cas de figure? est ce que on peut imaginer des prefix du type dfc-business, dfc-technical, dfc-glossary? Est il plus pertinent de fusionner (je ne sais pas encore comment) les 4 fichier OWL pour la publication?

**Comment by RachL** [comment]
@simonLouvet for the record the 4 prefix we've decided:

- DFCB for business onotlogy
- DFCP for product
- DFCT for tech
