### ISSUE TITLE
Create issues documenting the performance problem

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V3#26]
Following this work: 

https://github.com/datafoodconsortium/dfc-prototype-V3/issues/9

https://github.com/datafoodconsortium/dfc-prototype-V3/issues/7

https://github.com/datafoodconsortium/dfc-prototype-V3/issues/23

Showed a significant performance problem when importing data.

The task here is to create issues to document the 3 approaches:

- deepening our analysis
- change our protocol
- implement an asynchronous system

**Comment by simonLouvet** [comment]
https://docs.google.com/document/d/1ffERPEoHhwWyrQ0rqnpSBnJJ3SQctQfYpMQTUPqA8iQ/edit#heading=h.5e7wq6jjc33m

**Comment by simonLouvet** [comment]
0,25J
