### ISSUE TITLE
Update prototype with v1.4. fields

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V3#33]
**Description**

These fields where added in v1.4 we need to display them within the prototype:

- SKU
- Category
- Stock

On page http://proto.datafoodconsortium.org/#/x-catalog-supply

**Comment by simonLouvet** [comment]
@RachL tu peux me redire à quoi correspond SKU dans l'ontologie?

**Comment by simonLouvet** [comment]
@RachL Je me rends compte que intégrer les nouveaux champs va revenir à rapprocher des catalog item et plus des supplied product. Ca me pose beaucoup de question de designe. Comment faire une interface universelle de mise en correspondance de sujet (par leurs) id tout en tenant comptes des rapprochements déjà effectué.
exmpemle. Si le user à déjà rapproché des catalog item la rapprochement des supplied product associé devrait être grandement facilités voir automatique. Est ce que on peut prendre 30 min la semaine prochaine pour en parler tout les 2?

**Comment by RachL** [comment]
@simonLouvet yes! On en parle sur Slack

**Comment by simonLouvet** [comment]
2J
