### ISSUE TITLE
Handle PUSH

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V3#42]
Socleo's API is ready for push : we need to be able to push changes from the prototype to Socleo's product catalog

**Comment by RachL** [comment]
@simonLouvet What's the easiest for you to handle this in the UI? Can we edit directly on the tree?

Otherwise, I guess the best screen is this one for now?

![image](https://user-images.githubusercontent.com/6525576/115042183-887b4480-9ed3-11eb-946f-4fd464b533ad.png)

**Comment by simonLouvet** [comment]
1,5J
