### ISSUE TITLE
Put in place some tests

### ISSUE THREAD

**Issue by jdrouet** [datafoodconsortium/dfc-prototype-V3#45]
The dfc-app should have some tests and you could also communicate the coverage.

**Comment by RachL** [comment]
hey @jdrouet thank you for your comment! For now the app is only at prototype level: the scope has changed several times. So we didn't spent time yet on the automated test side. Are you planning to join our tech webinar on Wednesday?

**Comment by jdrouet** [comment]
I could join 🤔 when is it? Where?

**Comment by RachL** [comment]
@jdrouet have a look here for the registration link: https://www.datafoodconsortium.org/fr/nos-actualites/

If it does not work, join our slack : https://join.slack.com/t/datafoodconsortium/shared_invite/zt-83hxu18m-dUNX0qO1ryIWvkemWEpEgQ

Somebody will be able to help from there ;)
