### ISSUE TITLE
Document non LDP API

### ISSUE THREAD

**Issue by RachL** [datafoodconsortium/dfc-prototype-V3#53]
We need to document the non LDP version of the API under DFC standard. This includes:

- a clear documentation of the static API needed on platforms side

- a clear documentation of the static API available on the prototype

**Comment by RachL** [comment]
@simonLouvet just to check: is this linked with https://github.com/datafoodconsortium/dfc-prototype-V2/issues/66 ?

**Comment by simonLouvet** [comment]
0,5J
